# Candy Crush in Python - Part 1 - Game Representation

In this part of the tutorial we will get a basic game board set up and display it on the screen.

## Overview

We need a way to represent our game in our python program - this means we have to be able to store the state of the game - i.e. where all the gems are on our game board. We will use this representation to draw the game board on the screen and it is this representation we will modify when we want to change something on the board, e.g. when we swap two tiles on the board, or when we want to remove three of the same tile in a row or column.

## The Game Board

The first thing we need to do is create something to store our game board. The game board consists of a group of cells arranged as rows and columns. Each cell has a gem stone in it. There are 5 different types of gem - so we will use numbers 0-4 to represent each of the different gems:

|0&nbsp;&nbsp;&nbsp;&nbsp;|1&nbsp;&nbsp;&nbsp;&nbsp;|2&nbsp;&nbsp;&nbsp;&nbsp;|3&nbsp;&nbsp;&nbsp;&nbsp;|4&nbsp;&nbsp;&nbsp;&nbsp;|
|-|-|-|-|-|
|![0](https://brifly.github.io/python-lessons-images/diamond.png)| ![1](https://brifly.github.io/python-lessons-images/wdiamond.png) | ![2](https://brifly.github.io/python-lessons-images/precious-stone.png)|![3](https://brifly.github.io/python-lessons-images/jewels.png)|![4](https://brifly.github.io/python-lessons-images/gem.png)|

We will represent our game board in a data structure called an array. An array is structure that has a number of slots where we can store different pieces of data. Each slot of the game grid board will be one slot in the array - the slot will store the number that represents a particular gemstone. 

We need to be able to access the pieces of data in the array and to do this we use an index. Each piece of data in our array has its own index, which is basically the address for that piece of data. In our case we want to store the data in rows and columns so we need two indices, one for the row and one for the column. We will discuss how to do this below. For now, assuming we have this structure:


|  . | C0 | C1| C2|
| -- | -- | --| --|
| R0 | 0  | 1 | 2 |
| R1 | 3  | 4 | 0 |
| R2 | 1  | 2 | 3 |

It would represent the game board:

|.| C0 | C1 | C2 |
|-| -- | -- | -- |
| R0 | ![0](https://brifly.github.io/python-lessons-images/diamond.png) | ![1](https://brifly.github.io/python-lessons-images/wdiamond.png) | ![2](https://brifly.github.io/python-lessons-images/precious-stone.png) |
| R1 | ![3](https://brifly.github.io/python-lessons-images/jewels.png) | ![4](https://brifly.github.io/python-lessons-images/gem.png) | ![0](https://brifly.github.io/python-lessons-images/diamond.png) |
| R2 | ![1](https://brifly.github.io/python-lessons-images/wdiamond.png)| ![2](https://brifly.github.io/python-lessons-images/precious-stone.png)| ![3](https://brifly.github.io/python-lessons-images/jewels.png) |

In these examples R0,R1 and R2 are rows 0, 1 and 2 and C0, C1 and C2 are the columns 0, 1 and 2.

So the gem in row 1, column 2 is '0' - which represents the diamond.

### Lists

A python list, is just a simple list of things. It some values (e.g. numbers or strings) separated by commas, in between some square brackets e.g. [1,2,3] or ['A', 'B', 'C']. 

We will store the cells in each row in a single list. e.g. [0,1,2] would be the list for our first row in the example above. We will then store each of those rows in another list.

Lets begin by creating a list for each row: row1, row2, and row3:

In [1]:
row1 = [0, 1, 2]
row2 = [3, 4, 0]
row3 = [1, 2, 3]
print(row1)
print(row2)
print(row3)

[0, 1, 2]
[3, 4, 0]
[1, 2, 3]


We can then create our list of lists by putting those rows into another list:

In [2]:
rows = [row1, row2, row3]
print(rows)

[[0, 1, 2], [3, 4, 0], [1, 2, 3]]


Or we can do this in a single step:

In [3]:
rows = [
    [0, 1, 2],
    [3, 4, 0],
    [1, 2, 3]
]
print(rows)

[[0, 1, 2], [3, 4, 0], [1, 2, 3]]


### Numpy

We could leave our game representation here, but working with a list of lists is not ideal. Python has a library called numpy  which makes working with rows and columns of numbers easier, so we will convert our list of lists into a numpy array

To use numpy, we need to first import it:

In [6]:
import numpy as np

By putting 'as np' at the end, it means we can simply use the library by typing 'np' instead of the full name 'numpy'.

So now we turn our list of lists into a numpy array by calling np.array(...):

In [8]:
rows = [
    [0, 1, 2],
    [3, 4, 0],
    [1, 2, 3]
]
board = np.array(rows)
print(board)

[[0 1 2]
 [3 4 0]
 [1 2 3]]


We can already see it prints out a little nicer than the list of lists. 

We can do all the above in a single step:

In [9]:
board = np.array([
    [0, 1, 2],
    [3, 4, 0],
    [1, 2, 3]    
])
print(board)

[[0 1 2]
 [3 4 0]
 [1 2 3]]


## Display the Game Grid

When we print out the game grid we see the numbers in our array, but we would like to see what the actual game board looks like. To do this we will use a library called gamegrid using the import statement. 

In [10]:
from gamegrid import GameGrid
grid = GameGrid()

We can use grid.data =  &lt;Numpy Array> to setup our grid

In [11]:
board = np.array([
    [0,1,2],
    [3,4,0]
])

grid.data = board

To display the grid,we use the IPython.display function:

In [12]:
from IPython.display import display
display(grid)

GameGrid()

We can create a helper function called show_board that we can use to quickly show what a board looks like.

In [13]:
def show_board(board_array):
    grid = GameGrid()
    grid.data = board_array
    display(grid)

And lets test this function by showing a simple grid.

In [14]:
show_board(np.array([
    [0, 1, 2],
    [3, 4, 0]
]))

GameGrid()

## Summary

In this lesson we covered representing our game as a list of lists and then turning that into a numpy array to make it easier to work with. We also showed how to display our grid on the screen using the gamegrid library.

In the next lesson we will build the first bit of functionality for our game: [Swapping Tiles](Part2-Swapping.ipynb)